export const paths = {
  home: () => `/`,
  auth: () => `/auth`,

  warehouse: () => `/warehouses`,

  products: () => `/products`,

  receipt: () => `/inventory/receipt`,
  transaction: () => `/inventory/transaction`,
  returns: () => `/returns`,
  receiptId: (id: string) => `/inventory/receipt/${id}`,

  stock: () => `/stock`,
  stockHistory: () => `/stock/history`,
  stockHistoryDetails: (id: string) => `/stock/history/${id}`,
  sales: (id?: string) => id ? `/sales/${id}` : `/sales`,
  salesId: (id: string) => `/sales/${id}`,
  workers: () => `/workers`,
  workersId: (id: string) => `/workers/${id}`,
  customers: (id: string = '') => `/customers/${id}`,
  customersId: (id: string) => `/customers/${id}`,
  customerSales: (customerId: string, storeId: string) => `/customers/${customerId}/sales/${storeId}`,
  stores: () => `/stores`,
  storesId: (id: string) => `/stores/${id}`,
  suppliers: () => `/suppliers`,
  suppliersId: (id: string) => `/suppliers/${id}`,
  storeCustomers: (storeId: string) => `/stores/${storeId}/customers`,
  missingProducts: () => `/products/missing`,
  warehousesStock: () => `/warehouses/stock`,
  warehousesStockId: (id: string) => `/warehouses/stock/${id}`,
  productsId: (id: string) => `/products/${id}`,
  warehousesId: (id: string) => `/warehouses/${id}`,
  receiptsId: (id: string) => `/inventory/receipt/${id}`,
  stockId: (id: string) => `/stock/${id}`,
  transactionsId: (id: string) => `/inventory/transaction/${id}`,
  returnsId: (id: string) => `/returns/${id}`,
  expenses: () => `/expenses`,
}
